drop table if exists dwd_car_driver_mini_program_customer_df;
create table if not exists dwd_car_driver_mini_program_customer_df(
    id                    string     comment '主键'
    ,customer_id          string     comment '客户主键ID'    
    ,phone9               string     comment '手机号'
    ,open_id              string     comment '小程序 open_id'
    ,union_id             string     comment '小程序 union_id'    
    ,nick_name9           string     comment '昵称'    
    ,real_name9           string     comment '真实姓名'    
    ,avatar               string     comment '头像'
    ,gender               string     comment '性别 (0:未知 1:男 2:女 3:保密)'
    ,country              string     comment '国家'
    ,province             string     comment '省份'    
    ,city                 string     comment '城市'
    ,birthday             string     comment '生日'    
    ,last_auth_at         string     comment '最后一次授权时间'        
    ,last_login_at        string     comment '最后一次登录时间'        
    ,register_from        string     comment '注册来源 1-小程序 2-其它平台导入'        
    ,is_logout            string     comment '是否已退出登录 1-否 2-是'    
    ,vehicle_brand_id     string     comment '品牌 id'            
    ,brand_name           string     comment '品牌名称'    
    ,brand_logo           string     comment '品牌logo'    
    ,model_class          string     comment '车系'    
    ,vehicle_model_id     string     comment '车型id'            
    ,model_name           string     comment '车型名称'    
    ,sell_name9           string     comment '销售名称'    
    ,vehicle_name         string     comment '具体车型名称'        
    ,vehicle_id           string     comment '具体车型id'    
    ,product_year         string     comment '年份'        
    ,output_volume        string     comment '排量'        
    ,manufacturer         string     comment '厂家'        
    ,engine_code          string     comment '发动机型号'    
    ,license_plate9       string     comment '车牌号'        
    ,vin9                 string     comment '车辆vin码'
    ,remark               string     comment '用户备注信息'
    ,is_default           string     comment '是否默认车辆 ：1-默认车辆 2-非默认车辆'    
    ,store_no             string     comment '用户注册门店编号'   
    ,etl_load_time        string     comment '数据加载时间' 
)
partitioned by (pday string comment '时间分区')
stored as parquet
location 'boschfs://boschfs/warehouse/dwd_car_driver_mini_program_customer_df';