drop table if exists dwd_car_driver_mini_program_order_df;
create table if not exists dwd_car_driver_mini_program_order_df(
    id                              string     comment   ''   
    ,order_no                       string     comment   '订单号'               
    ,customer_id                    string     comment   '用户id'                   
    ,phone9                         string     comment   '用户手机号码'           
    ,open_id                        string     comment   '小程序open_id'               
    ,total_amount                   string     comment   '商品总价（优惠前） 单位：分'                   
    ,total_score                    string     comment   '所需总积分'                   
    ,preferential_price             string     comment   '优惠总金额，单位：分'                       
    ,activity_preferential_price    string     comment   '活动优惠金额，单位：分'                                   
    ,coupon_preferential_price      string     comment   '优惠券优惠金额，单位：分'                               
    ,freight                        string     comment   '运费 单位：分'               
    ,final_amount                   string     comment   '实际付款金额，单位：分'                   
    ,refund_amount                  string     comment   '已退款金额，单位：分'                   
    ,customer_coupon_id             string     comment   '优惠券ID (用户优惠券ID)'                       
    ,activity_id                    string     comment   '优惠活动id'                   
    ,pay_at                         string     comment   '支付时间'           
    ,cancelled_by                   string     comment   '订单取消方式 1 未取消，2 超时未支付取消，3 用户手动取消，4 后台手动取消'                   
    ,cancelled_at                   string     comment   '取消时间'                   
    ,is_del                         string     comment   '用户是否已删除 1=否 2=是'           
    ,quantity                       string     comment   '购买数量'               
    ,after_sale_num                 string     comment   '发生售后次数'                   
    ,is_all_refund                  string     comment   '是否全部退款 1=否 2=是'                   
    ,order_logistics_id             string     comment   '物流信息id'                       
    ,province                       string     comment   '省'               
    ,city                           string     comment   '市'           
    ,area                           string     comment   '区'           
    ,province_code                  string     comment   '省code'                   
    ,city_code                      string     comment   '市code'               
    ,area_code                      string     comment   '区code'               
    ,address9                       string     comment   '详细地址'               
    ,expire_at                      string     comment   '订单过期时间'               
    ,sync_status                    string     comment   '订单同步状态 0-未同步 1-同步成功 2-同步失败'                   
    ,from_type                      string     comment   '订单来源类型 0-普通订单 1-深圳会员活动'               
    ,from_id                        string     comment   '订单来源类型id 1-营销活动id'               
    ,created_at                     string     comment   '创建时间'               
    ,updated_at                     string     comment   '更新时间'               
    ,deleted_at                     string     comment   '删除时间'   
    ,etl_load_time                  string     comment   '数据加载时间'            
)
partitioned by (pday string comment '时间分区')
stored as parquet
location 'boschfs://boschfs/warehouse/dwd_car_driver_mini_program_order_df'